# Generated by Django 4.0.1 on 2022-01-15 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likeblog', '0002_alter_blog_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='likeblog.address'),
        ),
    ]
